export default {
  common: {
    primaryColor: '#7f9b7a',
    primaryColorHover: '#6e8d69',
    primaryColorPressed: '#5e7d59',
    primaryColorSuppl: '#7f9b7a',
    bodyColor: '#f5f3ee',
    cardColor: '#fbfaf7',
    modalColor: '#fbfaf7',
    popoverColor: '#fbfaf7',
    tableColor: '#fbfaf7',
    inputColor: '#ffffff',
    borderColor: '#ddd7cc',
    dividerColor: '#ebe6dc',
    textColor1: '#2f3a32',
    textColor2: '#465048',
    textColor3: '#5b635e',
    textColorDisabled: '#c5c0b6',
    placeholderColor: '#6e746f',
    borderRadiusSmall: '12px',
    borderRadius: '16px',
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", sans-serif',
    fontSize: '14px',
    fontSizeSmall: '13px',
    successColor: '#5a8a55',
    warningColor: '#b87b5d',
    errorColor: '#c0564a',
    infoColor: '#6e88a7',
  },
  Button: {
    borderRadiusSmall: '12px',
    borderRadiusMedium: '12px',
    borderRadiusLarge: '16px',
    heightSmall: '30',
    heightMedium: '36',
    heightLarge: '42',
    fontSizeSmall: '13px',
    fontSizeMedium: '14px',
  },
  DataTable: {
    thColor: '#f7f4ee',
    thTextColor: '#465048',
    tdColor: '#fbfaf7',
    tdColorHover: '#faf8f2',
    borderColor: '#eee7da',
    thFontWeight: '600',
    fontSize: '13px',
  },
  Tag: {
    borderRadius: '999px',
    heightSmall: '22',
    fontSizeSmall: '12px',
  },
  Input: {
    borderRadius: '12px',
    borderFocus: '1px solid #7f9b7a',
    borderHover: '1px solid #7f9b7a',
    boxShadowFocus: '0 0 0 3px rgba(127, 155, 122, 0.12)',
    caretColor: '#7f9b7a',
  },
  Select: {
    peers: {
      InternalSelection: {
        borderRadius: '12px',
        borderFocus: '1px solid #7f9b7a',
        borderHover: '1px solid #7f9b7a',
        boxShadowFocus: '0 0 0 3px rgba(127, 155, 122, 0.12)',
        caretColor: '#7f9b7a',
      },
    },
  },
  Tabs: {
    tabTextColorLine: '#5b635e',
    tabTextColorActiveLine: '#2f3a32',
    tabTextColorHoverLine: '#2f3a32',
    barColor: '#7f9b7a',
  },
  Modal: {
    borderRadius: '16px',
    color: '#fbfaf7',
  },
  Message: {
    borderRadius: '12px',
  },
  Card: {
    borderRadius: '16px',
    color: '#fbfaf7',
    borderColor: '#ddd7cc',
  },
}

export const CSS_VARS = {}
